# Generated by Django 5.2.8 on 2026-04-24 05:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academicTutoring", "0010_add_cancellation_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "simulator_type",
                    models.CharField(
                        choices=[
                            ("diagnostic", "Diagnóstico"),
                            ("reinforcement", "Refuerzo"),
                        ],
                        default="diagnostic",
                        max_length=20,
                        verbose_name="Tipo de simulador",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("closed", "Cerrado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("generating", "Generando..."),
                            ("done", "Listo"),
                            ("failed", "Error al generar"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado de generación",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ej: Diagnóstico — Cálculo diferencial",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=200, verbose_name="Materia o tema general"
                    ),
                ),
                (
                    "source_material_url",
                    models.URLField(
                        blank=True,
                        help_text="Material que subió el estudiante al solicitar la clase",
                        null=True,
                        verbose_name="URL del material fuente",
                    ),
                ),
                (
                    "source_material_text",
                    models.TextField(
                        blank=True,
                        help_text="Contenido extraído del material para pasarle al LLM",
                        null=True,
                        verbose_name="Texto del material fuente",
                    ),
                ),
                (
                    "weak_topics_context",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de temas en que el estudiante falló en simuladores previos",
                        verbose_name="Temas débiles detectados",
                    ),
                ),
                (
                    "generation_prompt",
                    models.TextField(
                        blank=True, null=True, verbose_name="Prompt enviado al LLM"
                    ),
                ),
                (
                    "generation_error",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Error de generación si falló",
                    ),
                ),
                (
                    "time_limit_per_question",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 significa sin límite de tiempo",
                        verbose_name="Tiempo límite por pregunta (segundos)",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Intentos máximos permitidos",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publicado el"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulators",
                        to="academicTutoring.classsession",
                        verbose_name="Sesión de clase",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_simulators",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante asignado",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "tutor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_simulators",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tutor que lo generó",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulador",
                "verbose_name_plural": "Simuladores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulatorAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        help_text="1 para el primero, 2 para el segundo, etc.",
                        verbose_name="Número de intento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "En progreso"),
                            ("completed", "Completado"),
                            ("abandoned", "Abandonado"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Estado del intento",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Puntaje (%)",
                    ),
                ),
                (
                    "correct_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Respuestas correctas"
                    ),
                ),
                (
                    "incorrect_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Respuestas incorrectas"
                    ),
                ),
                (
                    "unanswered_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sin responder"
                    ),
                ),
                (
                    "total_time_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tiempo total (segundos)"
                    ),
                ),
                (
                    "performance_by_topic",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Calculado automáticamente al finalizar el intento",
                        verbose_name="Desempeño por tema",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Inicio"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fin"),
                ),
                (
                    "simulator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="simulators.simulator",
                        verbose_name="Simulador",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulator_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intento de simulador",
                "verbose_name_plural": "Intentos de simulador",
                "ordering": ["-started_at"],
                "unique_together": {("simulator", "student", "attempt_number")},
            },
        ),
        migrations.CreateModel(
            name="SimulatorQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Orden de aparición"
                    ),
                ),
                (
                    "topic_tag",
                    models.CharField(
                        help_text='Ej: "derivadas implícitas", "herencia en POO", "balance de masas"',
                        max_length=100,
                        verbose_name="Tema",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Dificultad",
                    ),
                ),
                (
                    "statement",
                    models.TextField(verbose_name="Enunciado de la pregunta"),
                ),
                ("option_a", models.TextField(verbose_name="Opción A")),
                ("option_b", models.TextField(verbose_name="Opción B")),
                ("option_c", models.TextField(verbose_name="Opción C")),
                ("option_d", models.TextField(verbose_name="Opción D")),
                (
                    "correct_option",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="Opción correcta",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Explicación de la respuesta correcta",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "simulator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="simulators.simulator",
                        verbose_name="Simulador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta del simulador",
                "verbose_name_plural": "Preguntas del simulador",
                "ordering": ["simulator", "order"],
                "unique_together": {("simulator", "order")},
            },
        ),
        migrations.CreateModel(
            name="SimulatorResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_option",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        null=True,
                        verbose_name="Opción seleccionada",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Es correcta"),
                ),
                (
                    "time_spent_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tiempo en esta pregunta (segundos)"
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Respondida el"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="simulators.simulatorattempt",
                        verbose_name="Intento",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="simulators.simulatorquestion",
                        verbose_name="Pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta del simulador",
                "verbose_name_plural": "Respuestas del simulador",
                "ordering": ["question__order"],
                "unique_together": {("attempt", "question")},
            },
        ),
        migrations.CreateModel(
            name="StudentWeakTopicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Ej: Cálculo diferencial, Programación orientada a objetos",
                        max_length=200,
                        verbose_name="Materia",
                    ),
                ),
                (
                    "topic_tag",
                    models.CharField(
                        help_text='Ej: "derivadas implícitas", "herencia múltiple"',
                        max_length=100,
                        verbose_name="Tema específico",
                    ),
                ),
                (
                    "total_questions_seen",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de preguntas vistas"
                    ),
                ),
                (
                    "total_correct",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de respuestas correctas"
                    ),
                ),
                (
                    "cumulative_score_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Puntaje acumulado (%)",
                    ),
                ),
                (
                    "consecutive_failures",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Fallos consecutivos"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última vez visto"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weak_topic_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de tema débil",
                "verbose_name_plural": "Perfiles de temas débiles",
                "ordering": ["cumulative_score_pct"],
                "unique_together": {("student", "subject", "topic_tag")},
            },
        ),
    ]
