# Generated by Django 5.2.8 on 2026-03-23 03:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academicTutoring', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Materia')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('user_type', models.CharField(choices=[('tutor', 'Tutor'), ('client', 'Cliente')], max_length=10, verbose_name='Tipo de Usuario')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Cuéntanos un poco sobre ti', null=True, verbose_name='Biografía')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono')),
                ('avatar_url', models.URLField(blank=True, help_text='Enlace a tu foto de perfil', null=True, verbose_name='URL del Avatar')),
                ('is_minor', models.BooleanField(default=False, verbose_name='Es menor de edad')),
                ('parent_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del padre/tutor legal')),
                ('parent_email', models.EmailField(blank=True, help_text='Requerido para estudiantes menores de edad', max_length=254, null=True, verbose_name='Correo del padre/tutor legal')),
                ('city', models.CharField(default='Milagro', max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(default='Ecuador', max_length=100, verbose_name='País')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfiles de Clientes',
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Precio por hora de tutoría en dólares', max_digits=6, null=True, verbose_name='Tarifa por Hora (USD)')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Experiencia')),
                ('city', models.CharField(default='Milagro', max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(default='Ecuador', max_length=100, verbose_name='País')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subjects', models.ManyToManyField(blank=True, help_text='[DEPRECADO] Use subjects_taught en su lugar', related_name='tutors_legacy', to='accounts.subject', verbose_name='Materias (Legacy)')),
                ('subjects_taught', models.ManyToManyField(blank=True, help_text='Materias y niveles educativos que enseña este tutor', related_name='tutors', to='academicTutoring.subjectlevel', verbose_name='Materias y Niveles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Tutor',
                'verbose_name_plural': 'Perfiles de Tutores',
            },
        ),
    ]
