# Generated by Django 5.2.8 on 2026-03-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('tutor', 'Tutor'), ('client', 'Cliente')], default='', max_length=10, verbose_name='Tipo de Usuario'),
        ),
    ]
