# Generated by Django 5.2.8 on 2026-04-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_knowledgearea_tutorprofile_documents_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('tutor', 'Tutor'), ('client', 'Cliente')], max_length=10, verbose_name='Tipo de Usuario'),
        ),
    ]
