# Generated by Django 5.2.8 on 2026-04-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula / Identificación'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula / Identificación'),
        ),
    ]
