# Generated by Django 5.2.8 on 2026-04-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_birth_date_cedula_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='tutors_taught', to='accounts.subject', verbose_name='Materias que enseña'),
        ),
    ]
