# Generated by Django 5.2.8 on 2026-04-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subjects_taught_to_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='País'),
        ),
    ]
