# Generated by Django 5.2.8 on 2026-04-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_notification_read_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='clients/avatars/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='university_name',
            field=models.CharField(blank=True, help_text='Universidad actual del estudiante', max_length=200, null=True, verbose_name='Universidad donde estudia'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Sube tu foto de perfil', null=True, upload_to='tutors/avatars/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='is_foreign_institution',
            field=models.BooleanField(default=False, verbose_name='Institución en el extranjero'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='university_name',
            field=models.CharField(blank=True, help_text='Universidad donde enseña o trabajó', max_length=200, null=True, verbose_name='Universidad / Institución'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='university_url',
            field=models.URLField(blank=True, help_text='Solo para instituciones extranjeras', null=True, verbose_name='URL de la Institución'),
        ),
    ]
