# Generated by Django 5.2.8 on 2026-04-22 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_avatar_imagefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='avatar_url',
        ),
    ]
