# Generated by Django 5.2.8 on 2026-04-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='university_name',
            field=models.CharField(blank=True, help_text='Universidad actual del estudiante', max_length=200, null=True, verbose_name='Universidad donde estudia'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='university_name',
            field=models.CharField(blank=True, help_text='Universidad donde enseña o trabajó', max_length=200, null=True, verbose_name='Universidad / Institución'),
        ),
    ]
