# Generated by Django 5.2.8 on 2026-04-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_university_name_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='document_file',
            field=models.FileField(blank=True, help_text='Constancia de matrícula, carnet u otro documento de tu institución educativa', null=True, upload_to='documents/students/', verbose_name='Documento institucional'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='document_file',
            field=models.FileField(blank=True, help_text='PDF, imagen u otro archivo que acredite tu experiencia', null=True, upload_to='documents/tutors/', verbose_name='Documento (CV / Credencial)'),
        ),
    ]
