# Generated by Django 5.2.8 on 2026-04-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_document_file_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Desactivar cuando documentación está pendiente de revisión', verbose_name='Tutor aprobado'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='welcome_shown',
            field=models.BooleanField(default=False, verbose_name='Mensaje de bienvenida mostrado'),
        ),
    ]
