# Generated by Django 5.2.8 on 2026-04-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_tutor_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='institutional_credential_file',
            field=models.FileField(blank=True, help_text='Carnet o ID de la universidad/institución donde enseñas actualmente', null=True, upload_to='documents/tutors/institutional/', verbose_name='Credencial institucional'),
        ),
    ]
