# Generated by Django 5.2.8 on 2026-04-25 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicTutoring', '0015_platformconfig_full_rewrite_institution_sessionmaterial'),
        ('accounts', '0018_add_institutional_credential_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='cv_file',
            field=models.FileField(blank=True, help_text='CV en formato PDF. Máximo 5MB.', null=True, upload_to='documents/tutors/cv/', verbose_name='Currículum Vitae (PDF)'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='education_certificate_file',
            field=models.FileField(blank=True, help_text='Título, diploma o certificado que acredite el nivel declarado', null=True, upload_to='documents/tutors/education/', verbose_name='Certificado de nivel educativo (PDF)'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('bachiller', 'Bachiller'), ('tecnico', 'Técnico / Tecnólogo'), ('universitario', 'Universitario / Egresado'), ('posgrado', 'Posgrado (Maestría / Doctorado)')], default='', help_text='Nivel educativo más alto alcanzado', max_length=20, verbose_name='Nivel de educación'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('desempleado', 'Desempleado / Freelancer'), ('empleado_no_docente', 'Empleado (no sector educativo)'), ('docente_activo', 'Docente activo en institución')], default='', help_text='Estado laboral actual del tutor', max_length=30, verbose_name='Situación laboral'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutors', to='academicTutoring.institution', verbose_name='Institución donde labora'),
        ),
    ]
