# Generated by Django 5.2.8 on 2026-04-25 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicTutoring', '0015_platformconfig_full_rewrite_institution_sessionmaterial'),
        ('accounts', '0019_add_tutor_cv_employment_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='enrollment_file',
            field=models.FileField(blank=True, help_text='Carnet estudiantil vigente o constancia de matrícula', null=True, upload_to='documents/students/enrollment/', verbose_name='Carnet o constancia de matrícula'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='id_document_file',
            field=models.FileField(blank=True, help_text='Cédula o documento de identidad vigente', null=True, upload_to='documents/students/id/', verbose_name='Cédula de identidad (PDF o imagen)'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academicTutoring.institution', verbose_name='Institución educativa'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='student_type',
            field=models.CharField(blank=True, choices=[('universitario', 'Estudiante universitario'), ('autodidacta', 'Autodidacta')], default='', help_text='¿Eres estudiante de una institución educativa o aprendiz independiente?', max_length=20, verbose_name='Tipo de estudiante'),
        ),
    ]
