# Generated by Django 5.2.8 on 2026-04-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_client_student_type_documents_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='knowledge_document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/tutors/knowledge/', verbose_name='Documento de conocimientos'),
        ),
    ]
