[phases.setup]
nixPkgs = ["python312", "gcc", "gdal"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["chmod +x build.sh && ./build.sh"]

[phases.release]
cmds = ["python manage.py migrate"]

[start]
cmd = "bash start.sh"
