# Generated by Django 5.2.8 on 2025-11-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='host_join_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Host'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID de Reunión'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='meeting_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contraseña de Reunión'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='meeting_platform',
            field=models.CharField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('custom', 'Personalizado')], default='google_meet', max_length=20, verbose_name='Plataforma de Reunión'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='meeting_started',
            field=models.BooleanField(default=False, verbose_name='Reunión Iniciada'),
        ),
    ]
