# Generated by Django 5.2.8 on 2025-12-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_classsession_host_join_url_classsession_meeting_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificacionExpansion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "ciudad_deseada",
                    models.CharField(max_length=100, verbose_name="Ciudad Deseada"),
                ),
                (
                    "provincia_deseada",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Provincia Deseada",
                    ),
                ),
                (
                    "pais",
                    models.CharField(
                        default="Ecuador", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP del Visitante"
                    ),
                ),
                (
                    "ciudad_detectada",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ciudad Detectada (IP)",
                    ),
                ),
                (
                    "notificado",
                    models.BooleanField(
                        default=False, verbose_name="Notificación Enviada"
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Solicitud"
                    ),
                ),
                (
                    "fecha_notificacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Notificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación de Expansión",
                "verbose_name_plural": "Notificaciones de Expansión",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.AlterModelOptions(
            name="tutorlead",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Tutor Lead",
                "verbose_name_plural": "Tutor Leads",
            },
        ),
        migrations.CreateModel(
            name="CiudadHabilitada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ciudad", models.CharField(max_length=100, verbose_name="Ciudad")),
                (
                    "provincia",
                    models.CharField(max_length=100, verbose_name="Provincia/Estado"),
                ),
                (
                    "pais",
                    models.CharField(
                        default="Ecuador", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si está activo, los usuarios de esta ciudad pueden acceder al servicio",
                        verbose_name="Servicio Activo",
                    ),
                ),
                (
                    "fecha_habilitacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Habilitación"
                    ),
                ),
                (
                    "orden_prioridad",
                    models.IntegerField(
                        default=100,
                        help_text="Menor número = mayor prioridad en el listado",
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas Administrativas"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciudad Habilitada",
                "verbose_name_plural": "Ciudades Habilitadas",
                "ordering": ["orden_prioridad", "ciudad"],
                "unique_together": {("ciudad", "provincia", "pais")},
            },
        ),
    ]
