# Generated by Django 5.2.8 on 2025-12-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_subject_tutorprofile_hourly_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                help_text="Enlace a tu foto de perfil",
                null=True,
                verbose_name="URL del Avatar",
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Cuéntanos un poco sobre ti",
                null=True,
                verbose_name="Biografía",
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Número de teléfono"
            ),
        ),
    ]
