"""
Django settings for subjectSupport project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY must be set in .env file - NO default for security
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY not found in environment variables!\n"
        "Create a .env file in the project root with:\n"
        "SECRET_KEY=your-secret-key-here\n"
        "Use .env.example as template."
    )

# Additional validation: reject insecure default keys
INSECURE_KEYS = [
    'django-insecure-$)r=921il+p(swd4he)@p3d8u!st=)7@b77rr4p(i7@^scfkc1',
    'change-me-to-a-random-secret-key-min-50-chars',
    'omae_o_zutto_aishiteru',
]
if SECRET_KEY in INSECURE_KEYS:
    raise ValueError(
        "Using an insecure SECRET_KEY!\n"
        "Generate a new one with:\n"
        "python -c \"import secrets; print(''.join(secrets.choice('abcdefghijklmnopqrstuvwxyz0123456789!@#%%^&*(-_=+)') for i in range(50)))\"\n"
        "And update it in your .env file."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Parse ALLOWED_HOSTS from environment variable
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
if not ALLOWED_HOSTS or ALLOWED_HOSTS == ['']:
    if DEBUG:
        # Default to localhost in development
        ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    else:
        raise ValueError(
            "ALLOWED_HOSTS must be set in production!\n"
            "Add to your .env file or environment variables:\n"
            "ALLOWED_HOSTS=.onrender.com,yourdomain.com"
        )

# Add 'testserver' for Django TestClient (used in unit tests)
if DEBUG and 'testserver' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('testserver')

# CSRF Protection - Trusted origins for AJAX/form submissions
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
if not CSRF_TRUSTED_ORIGINS or CSRF_TRUSTED_ORIGINS == ['']:
    if DEBUG:
        # Default for local development
        CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']
    else:
        # In production, this should be set explicitly
        CSRF_TRUSTED_ORIGINS = []

# Geolocalización - Restricción geográfica del servicio
SKIP_GEO_CHECK = os.getenv('SKIP_GEO_CHECK', 'False') == 'True'

# Application definition

# Determinar si GIS está disponible (necesario para GeoDjango)
GIS_AVAILABLE = False
if not DEBUG:
    # En producción siempre usar GIS (PostGIS estará disponible)
    GIS_AVAILABLE = True
else:
    # En desarrollo LOCAL, deshabilitar temporalmente GIS (GDAL no instalado)
    # Para habilitar: instalar GDAL y descomentar la siguiente línea
    GIS_AVAILABLE = False
    
    # # Descomentar esto cuando GDAL esté instalado en Windows
    # try:
    #     from django.contrib.gis.db.backends.spatialite.base import DatabaseWrapper  # noqa: F401
    #     GIS_AVAILABLE = True
    # except (ImportError, Exception):
    #     GIS_AVAILABLE = False
    #     import warnings
    #     warnings.warn(
    #         "GDAL not available in development. GIS features disabled locally. "
    #         "To enable: install OSGeo4W (Windows) or gdal-bin (Linux/Mac). "
    #         "Production will use PostGIS normally."
    #     )

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Agregar django.contrib.gis solo si está disponible
if GIS_AVAILABLE:
    INSTALLED_APPS.append('django.contrib.gis')

INSTALLED_APPS += [
    'apps.academicTutoring.accounts',
    'apps.academicTutoring.core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Debe ir justo después de SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Middleware de restricción geográfica (debe ir después de SessionMiddleware)
    'apps.academicTutoring.core.middleware.GeoRestrictionMiddleware',
]

ROOT_URLCONF = 'subjectSupport.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'subjectSupport.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

if DEBUG:
    # Development: Intentar usar SpatiaLite para GeoDjango si está disponible
    # Si no está disponible (GDAL no instalado), usar SQLite normal
    # NOTA: En desarrollo local, si necesitas funcionalidad GIS completa:
    #   - Windows: instala OSGeo4W (https://trac.osgeo.org/osgeo4w/)
    #   - Linux/Mac: instala gdal (apt-get install gdal-bin python3-gdal)
    try:
        from django.contrib.gis.db.backends.spatialite.base import DatabaseWrapper  # noqa: F401
        DATABASES = {
            'default': {
                'ENGINE': 'django.contrib.gis.db.backends.spatialite',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
    except (ImportError, Exception):
        # Fallback: SQLite normal sin capacidades GIS
        # Las migraciones GIS se crearán pero no se ejecutarán en desarrollo
        import warnings
        warnings.warn(
            "GDAL not found. Using standard SQLite. "
            "Install GDAL/SpatiaLite for full GIS support in development. "
            "Production (PostGIS) will work normally."
        )
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    # Production: PostgreSQL con PostGIS para GeoDjango
    db_config = dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )
    # Cambiar engine a PostGIS backend
    db_config['ENGINE'] = 'django.contrib.gis.db.backends.postgis'
    DATABASES = {
        'default': db_config
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'email', 'name'),
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Locale paths for custom translations
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Available languages
LANGUAGES = [
    ('es', _('Spanish')),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Additional static files directories (if needed)
STATICFILES_DIRS = [
    # BASE_DIR / 'static',  # Uncomment if you have a global static folder
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'landing'

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@subjectsupport.com'
EMAIL_SUBJECT_PREFIX = '[SubjectSupport] '

# Security settings for production
if not DEBUG:
    # HTTPS/SSL
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Security headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'INFO',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
