# Generated by Django 5.2.8 on 2025-11-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(default='Quito', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='country',
            field=models.CharField(default='Ecuador', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='city',
            field=models.CharField(default='Quito', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='country',
            field=models.CharField(default='Ecuador', max_length=100, verbose_name='País'),
        ),
    ]
