# Generated by Django 5.2.8 on 2025-12-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile_city_clientprofile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Materia')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por hora de tutoría en dólares', max_digits=6, null=True, verbose_name='Tarifa por Hora (USD)'),
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Materias que enseña este tutor', related_name='tutors', to='accounts.subject', verbose_name='Materias'),
        ),
    ]
