# Generated by Django 5.2.8 on 2025-12-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_clientprofile_avatar_url_clientprofile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Número de teléfono"
            ),
        ),
    ]
