# Generated by Django 5.2.8 on 2026-03-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Materia')),
                ('scheduled_date', models.DateField(verbose_name='Fecha')),
                ('scheduled_time', models.TimeField(verbose_name='Hora')),
                ('duration', models.IntegerField(choices=[(60, '1 hora'), (90, '1.5 horas'), (120, '2 horas'), (150, '2.5 horas'), (180, '3 horas')], default=60, verbose_name='Duración (minutos)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('meeting_platform', models.CharField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('custom', 'Personalizado')], default='google_meet', max_length=20, verbose_name='Plataforma de Reunión')),
                ('meeting_url', models.URLField(blank=True, null=True, verbose_name='URL de Reunión')),
                ('meeting_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID de Reunión')),
                ('meeting_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contraseña de Reunión')),
                ('host_join_url', models.URLField(blank=True, null=True, verbose_name='URL de Host')),
                ('meeting_started', models.BooleanField(default=False, verbose_name='Reunión Iniciada')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sesión de Clase',
                'verbose_name_plural': 'Sesiones de Clase',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Primaria, Secundaria, Bachillerato, Universidad', max_length=100, unique=True, verbose_name='Nombre del Nivel')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización (menor primero)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ciudad_deseada', models.CharField(max_length=100, verbose_name='Ciudad Deseada')),
                ('provincia_deseada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia Deseada')),
                ('pais', models.CharField(default='Ecuador', max_length=100, verbose_name='País')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del Visitante')),
                ('ciudad_detectada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad Detectada (IP)')),
                ('notificado', models.BooleanField(default=False, verbose_name='Notificación Enviada')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Notificación')),
            ],
            options={
                'verbose_name': 'Notificación de Expansión',
                'verbose_name_plural': 'Notificaciones de Expansión',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(help_text='Nombre de la ciudad que cubre esta área de servicio', max_length=100, unique=True, verbose_name='Ciudad')),
                ('area', models.TextField(default='POLYGON EMPTY', help_text='Polígono en formato WKT. En producción se usará PolygonField de PostGIS.', verbose_name='Área de Cobertura (WKT)')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, usuarios dentro del polígono tendrán acceso al servicio', verbose_name='Activo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del área (ej: Cantón Milagro, Provincia Guayas)', null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Área de Servicio',
                'verbose_name_plural': 'Áreas de Servicio',
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Materia por Nivel',
                'verbose_name_plural': 'Materias por Nivel',
                'ordering': ['level__order', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='TutorLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tutor Lead',
                'verbose_name_plural': 'Tutor Leads',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
