# Generated by Django 5.2.8 on 2026-03-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicTutoring', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorlead',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración'),
        ),
    ]
