# Generated by Django 5.2.8 on 2026-04-02 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicTutoring', '0003_tutorlead_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2, unique=True, verbose_name='Código de País')),
                ('country_name', models.CharField(max_length=100, verbose_name='Nombre del País')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('geo_restricted', models.BooleanField(default=False, verbose_name='Geo Restringido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['country_name'],
            },
        ),
        migrations.AddField(
            model_name='servicearea',
            name='country_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='academicTutoring.countryconfig', verbose_name='Configuración de País'),
        ),
    ]
