# Generated by Django 5.2.8 on 2026-04-02 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicTutoring', '0004_countryconfig_servicearea_country_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='city_name',
            field=models.CharField(help_text='Nombre de la ciudad que cubre esta área de servicio', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='tutorlead',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Expiración'),
        ),
        migrations.AlterUniqueTogether(
            name='servicearea',
            unique_together={('city_name', 'country_config')},
        ),
    ]
