# Generated by Django 5.2.8 on 2026-04-02 15:42

import django.db.models.deletion
from django.db import migrations, models


def clear_service_areas(apps, schema_editor):
    """
    En latam-mvp geo_restricted=False para todos los países.
    ServiceArea no se usa — limpiar para evitar FK violation
    antes de aplicar el constraint NOT NULL en country_config.
    """
    ServiceArea = apps.get_model('academicTutoring', 'ServiceArea')
    ServiceArea.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academicTutoring', '0005_alter_servicearea_city_name_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_service_areas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='servicearea',
            name='country_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='academicTutoring.countryconfig', verbose_name='Configuración de País'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorlead',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración'),
        ),
    ]