# Generated by Django 5.2.8 on 2026-04-02 19:59

from django.db import migrations


def insert_latam_countries(apps, schema_editor):
    CountryConfig = apps.get_model('academicTutoring', 'CountryConfig')
    countries = [
        ('MX', 'México'),
        ('GT', 'Guatemala'),
        ('BZ', 'Belice'),
        ('HN', 'Honduras'),
        ('SV', 'El Salvador'),
        ('NI', 'Nicaragua'),
        ('CR', 'Costa Rica'),
        ('PA', 'Panamá'),
        ('CO', 'Colombia'),
        ('VE', 'Venezuela'),
        ('EC', 'Ecuador'),
        ('PE', 'Perú'),
        ('BO', 'Bolivia'),
        ('CL', 'Chile'),
        ('AR', 'Argentina'),
        ('UY', 'Uruguay'),
        ('PY', 'Paraguay'),
        ('BR', 'Brasil'),
        ('GY', 'Guyana'),
        ('SR', 'Surinam'),
    ]
    for code, name in countries:
        CountryConfig.objects.get_or_create(
            country_code=code,
            defaults={
                'country_name': name,
                'active': True,
                'geo_restricted': False
            }
        )


def remove_latam_countries(apps, schema_editor):
    CountryConfig = apps.get_model('academicTutoring', 'CountryConfig')
    codes = ['MX','GT','BZ','HN','SV','NI','CR','PA','CO','VE',
             'EC','PE','BO','CL','AR','UY','PY','BR','GY','SR']
    CountryConfig.objects.filter(country_code__in=codes).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('academicTutoring', '0006_alter_servicearea_country_config_and_more'),
    ]
    operations = [
        migrations.RunPython(insert_latam_countries, remove_latam_countries),
    ]
