# Generated by Django 5.2.8 on 2026-04-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicTutoring', '0008_caribe_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='material_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Material de clase (URL)'),
        ),
    ]
