# Generated by Django 5.2.8 on 2026-04-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicTutoring', '0009_classsession_material_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de cancelación'),
        ),
    ]
