# Generated by Django 5.2.8 on 2026-04-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicTutoring', '0010_add_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_tutor_document', models.BooleanField(default=False, help_text='Si activo, el tutor debe subir CV o credencial al registrarse', verbose_name='Exigir documento a tutores')),
                ('require_student_document', models.BooleanField(default=False, help_text='Si activo, el estudiante debe subir documento institucional al registrarse', verbose_name='Exigir documento a estudiantes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Plataforma',
                'verbose_name_plural': 'Configuración de Plataforma',
            },
        ),
    ]
