# Generated by Django 5.2.8 on 2026-04-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicTutoring', '0011_add_platform_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='enable_minor_accounts',
            field=models.BooleanField(default=False, help_text='Si activo, muestra el flujo de registro para menores en la app', verbose_name='Habilitar cuentas de menores de edad'),
        ),
    ]
