# Generated by Django 5.2.8 on 2026-04-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicTutoring', '0012_add_enable_minor_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='require_student_university',
            field=models.BooleanField(default=True, help_text='Si activo, el estudiante debe declarar su institución educativa al registrarse', verbose_name='Exigir universidad al estudiante'),
        ),
    ]
