# Generated by Django 5.2.8 on 2026-04-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicTutoring', '0013_add_require_student_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='require_tutor_knowledge_document',
            field=models.BooleanField(default=False, help_text='Si activo, el tutor debe subir CV, título o certificados. Su cuenta quedará pendiente de aprobación hasta revisión del admin.', verbose_name='Exigir documento de conocimiento al tutor'),
        ),
    ]
