# Generated by Django 5.2.8 on 2026-04-25 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicTutoring', '0014_add_require_knowledge_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre de la institución')),
                ('type', models.CharField(choices=[('universidad', 'Universidad'), ('instituto', 'Instituto Técnico/Tecnológico'), ('colegio', 'Colegio'), ('escuela', 'Escuela')], default='universidad', max_length=20, verbose_name='Tipo')),
                ('province', models.CharField(blank=True, default='', max_length=100, verbose_name='Provincia')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad')),
                ('is_manual', models.BooleanField(default=False, help_text='True si fue ingresada por un usuario, no del dataset oficial', verbose_name='Ingresada manualmente')),
                ('needs_review', models.BooleanField(default=False, help_text='True para entradas manuales hasta verificación', verbose_name='Requiere revisión admin')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='allow_manual_institution_entry',
            field=models.BooleanField(default=True, help_text='Si la institución no está en la lista, el usuario puede ingresarla manualmente. Queda en revisión del admin', verbose_name='Permitir ingreso manual de institución'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='allowed_file_types',
            field=models.CharField(default='pdf,jpg,jpeg,png,doc,docx,ppt,pptx,xlsx', help_text='Extensiones separadas por coma (sin puntos)', max_length=200, verbose_name='Tipos de archivo permitidos'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='enable_deposit_voucher',
            field=models.BooleanField(default=False, help_text='Permite pago manual con comprobante revisado por admin (Fase 3)', verbose_name='Habilitar pago por comprobante de depósito'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='enable_institution_search',
            field=models.BooleanField(default=True, help_text='Permite buscar instituciones del dataset MINEDUC en el registro', verbose_name='Habilitar búsqueda de instituciones'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='enable_payphone',
            field=models.BooleanField(default=False, help_text='Activa la pasarela de pago PayPhone (Fase 3)', verbose_name='Habilitar PayPhone'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='max_file_size_mb',
            field=models.IntegerField(default=5, help_text='Límite de tamaño por archivo subido en la plataforma', verbose_name='Tamaño máximo de archivo (MB)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='max_session_materials',
            field=models.IntegerField(default=7, help_text='Cantidad máxima de materiales que se pueden adjuntar a una sesión', verbose_name='Máximo de archivos por sesión'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='max_subjects_per_tutor',
            field=models.IntegerField(default=5, help_text='Cantidad máxima de materias que un tutor puede seleccionar', verbose_name='Máximo de materias por tutor'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='min_student_age',
            field=models.IntegerField(default=15, help_text='Edad mínima absoluta para registrarse como estudiante', verbose_name='Edad mínima de estudiante'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='min_tutor_age',
            field=models.IntegerField(default=18, help_text='Edad mínima para registrarse como tutor', verbose_name='Edad mínima de tutor'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='platform_commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje que retiene la plataforma de cada sesión pagada (Fase 3)', max_digits=5, verbose_name='Comisión de plataforma (%)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='refund_policy_hours',
            field=models.IntegerField(default=24, help_text='Cancelaciones antes de este plazo reciben reembolso completo (Fase 3)', verbose_name='Horas para reembolso completo'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='require_student_enrollment_certificate',
            field=models.BooleanField(default=True, help_text='Carnet o constancia de matrícula para estudiantes universitarios', verbose_name='Exigir carnet/constancia de matrícula'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='require_student_id_document',
            field=models.BooleanField(default=True, help_text='Cédula obligatoria para estudiantes mayores de edad', verbose_name='Exigir cédula al estudiante'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='require_tutor_cv',
            field=models.BooleanField(default=True, help_text='CV en PDF obligatorio en el registro del tutor', verbose_name='Exigir CV al tutor'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='require_tutor_education_certificate',
            field=models.BooleanField(default=False, help_text='Certificado que acredite el nivel educativo declarado por el tutor', verbose_name='Exigir certificado de nivel educativo'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='require_tutor_institutional_credential',
            field=models.BooleanField(default=False, help_text='Carnet o ID de institución. Requerido si el tutor es docente activo', verbose_name='Exigir credencial institucional al tutor'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='session_cancellation_hours',
            field=models.IntegerField(default=24, help_text='Aplica cuando los pagos estén activos (Fase 3)', verbose_name='Horas mínimas para cancelar sin penalización'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='enable_minor_accounts',
            field=models.BooleanField(default=False, help_text='Si activo, muestra el flujo de registro para menores con tutor legal', verbose_name='Habilitar cuentas de menores de edad'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='require_student_document',
            field=models.BooleanField(default=False, help_text='Documento institucional genérico para el estudiante', verbose_name='Exigir documento institucional al estudiante'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='require_student_university',
            field=models.BooleanField(default=True, help_text='El estudiante debe declarar su institución educativa al registrarse', verbose_name='Exigir universidad al estudiante'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='require_tutor_document',
            field=models.BooleanField(default=False, help_text='Documento genérico (CV o credencial). Activa flujo de aprobación', verbose_name='Exigir documento genérico al tutor'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='require_tutor_knowledge_document',
            field=models.BooleanField(default=False, help_text='Títulos, certificados o CV académico. Activa flujo de aprobación hasta revisión del admin', verbose_name='Exigir documento de conocimiento al tutor'),
        ),
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('url', 'Enlace URL'), ('file', 'Archivo')], max_length=10, verbose_name='Tipo')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, null=True, upload_to='sessions/materials/', verbose_name='Archivo')),
                ('filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre del archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academicTutoring.classsession', verbose_name='Sesión')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Material de Sesión',
                'verbose_name_plural': 'Materiales de Sesión',
                'ordering': ['created_at'],
            },
        ),
    ]
